// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef Fl_Slide_h
#define Fl_Slide_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include"Fl_Gl_Slide.H"
#include <FL/Fl_Slider.H>

class fl_slide_win {
public:
  fl_slide_win();
  Fl_Double_Window *slide_win;
private:
  inline void cb_Draw_i(Fl_Button*, void*);
  static void cb_Draw(Fl_Button*, void*);
  inline void cb_Icono_i(Fl_Button*, void*);
  static void cb_Icono(Fl_Button*, void*);
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  Fl_Gl_Slide *gl_slide;
  Fl_Slider *gl_zoom;
private:
  inline void cb_gl_zoom_i(Fl_Slider*, void*);
  static void cb_gl_zoom(Fl_Slider*, void*);
public:
  void close();
  void show();
  void icono();
};
#endif
