// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "Fl_Slide.h"

int main(void) {
  fl_slide_win * win = new fl_slide_win();
  win->show();
  Fl::run();
  return 0;
}
